Metadata:
  AmerifluxID:
  lat: 69.2264167
  long: -135.2519067
  siteID: SCL
  startYear:
  stopYear:
  timezone:
rawData:
  preEvaluate: |-
    #Codespace for preEvaluate corrections
    # Filter out bad SlrW (covered by snow/ice)
    rawData.loc[rawData.index>'2025-03-01','MetWx2024.101-SlrW_AVG']=np.nan
    # Correct CH4
    LI7700_amb_tmpr="Flux2025.LI7700_amb_tmpr"
    LI7700_amb_press="Flux2025.LI7700_amb_press"
    FCH4_mass="Flux2025.FCH4_mass"
    def kTP(TP,t2,t1,p2,p1,c):
    	T,P = TP
    	return (t2*T**2+t1*T+p2*P**2+p1*P+c)
    TP = np.vstack(((rawData[LI7700_amb_tmpr].values+273.15),rawData[LI7700_amb_press].values))
    k = kTP(TP,*[6.37856586e-06,-2.69695519e-03,8.32661719e-05,-7.24864231e-03,1.11848651e+00])
    rawData[FCH4_mass] = rawData[FCH4_mass]*rawData[LI7700_amb_press]/((rawData[LI7700_amb_tmpr]+273.15)*8.314*k)
    # Unit conversion
    rawData["Flux2025.FCH4"] = rawData[FCH4_mass]/16.04*1e-3
    rawData["Flux2025.FCO2"] = rawData["Flux2025.FC_mass"]/44.01*1e3
    # Convert Flux2025 Foken 2003 to Mauder & Foken 2004
    rawData["Flux2025.H_QC"] = (rawData["Flux2025.H_QC"]/3).fillna(-9999).astype(int)
    rawData["Flux2025.LE_QC"] = (rawData["Flux2025.LE_QC"]/3).fillna(-9999).astype(int)
    rawData["Flux2025.FCO2_QC"] = (rawData["Flux2025.FC_QC"]/3).fillna(-9999).astype(int)
    # Convert AGC
    rawData["Flux2024.co2_signal"] = (100-(rawData["Flux2024.mean_value_AGC_LI-7500"]-rawData["Flux2024.mean_value_AGC_LI-7500"].min())).dropna()
    rawData["Flux2024.h2o_signal"] = (100-(rawData["Flux2024.mean_value_AGC_LI-7500"]-rawData["Flux2024.mean_value_AGC_LI-7500"].min())).dropna()
    rawData["Flux2025.H2O_sig_strgth_Min"]*=100
    rawData["Flux2025.CO2_sig_strgth_Min"]*=100
  Met2024: &Met2024.inputDates
  - '2024-07-20T21:00:00+00:00'
  - '2024-09-13T00:30:00+00:00'
  MetWx2024: &MetWx2024.inputDates
  - '2024-09-13T22:30:00+00:00'
  - '2025-06-19T17:30:00+00:00'
  Flux2024: &Flux2024.inputDates
  - '2024-07-25T03:30:00+00:00'
  - '2024-09-13T00:30:00+00:00'
  Flux2025: &Flux2025.inputDates
  - '2025-07-30T00:00:00+00:00'
  - '2026-04-11T00:00:00+00:00'
  SSM_TS: &SSM_TS.inputDates
  - '2024-07-20T21:00:00+00:00'
  - '2025-07-18T16:00:00+00:00'
  NARR: &NARR.inputDates
  - '2024-01-01T00:00:00+00:00'
  - '2026-03-31T21:00:00+00:00'
Processing:
  FirstStage:
    posix_time:
      variableName: posix_time
      units: s
      dtype: int64
      inputFiles:
        Met2024.posix_time: *Met2024.inputDates
        MetWx2024.posix_time: *MetWx2024.inputDates
        Flux2024.posix_time: *Flux2024.inputDates
        Flux2025.posix_time: *Flux2025.inputDates
        SSM_TS.posix_time: *SSM_TS.inputDates
        NARR.posix_time: *NARR.inputDates
      minMax:
      - -.inf
      - .inf
      clamped_minMax:
      - -.inf
      - .inf
      dependent: []
      linearRescale:
      notes: default time-trace (seconds since unix epoch)
    TA_1_1_1:
      variableName: TA_1_1_1
      units: C
      # dtype: float32
      inputFiles:
        Met2024.AirTC_Avg: *Met2024.inputDates
        MetWx2024.101-AirTC_AVG: *MetWx2024.inputDates
        Flux2025.TA_1_1_3: *Flux2025.inputDates
      minMax:
      - -50
      - 50
    TA_NARR:
      variableName: TA_NARR
      units: K
      # dtype: float32
      inputFiles:
        NARR.air_2m: *NARR.inputDates
      minMax:
      - 223.15
      - 323.15
    RH_1_1_1:
      variableName: RH_1_1_1
      units: C
      # dtype: float32
      inputFiles:
        Met2024.RH: *Met2024.inputDates
        MetWx2024.101-RH: *MetWx2024.inputDates
        Flux2025.RH_1_1_2: *Flux2025.inputDates
      minMax:
      - -10
      - 110
      clampedMinMax:
      - 0
      - 100
    SW_IN_1_1_1:
      variableName: SW_IN_1_1_1
      units: Wm-2
      inputFiles:
        Met2024.SlrW_Avg: *Met2024.inputDates
        MetWx2024.101-SlrW_AVG: #*MetWx2024.inputDates
        - '2024-09-13T22:30:00+00:00'
        - '2025-03-01T23:30:00+00:00'
        Flux2025.SW_IN: *Flux2025.inputDates
    SW_IN_NARR:
      variableName: SW_IN_NARR
      units: Wm-2
      inputFiles:
        NARR.dswrf: *NARR.inputDates
    ustar:
      variableName: ustar
      units: ms-1
      inputFiles:
        Flux2024.ustar: *Flux2024.inputDates
        Flux2025.USTAR: *Flux2025.inputDates
    H:
      variableName: H
      units: W m-2
      inputFiles:
        Flux2024.H: *Flux2024.inputDates
        Flux2025.H: *Flux2025.inputDates
      dependent:
      - H_QC
    H_QC:
      variableName: H_QC
      units: arb
      inputFiles:
        Flux2024.qc_H: *Flux2024.inputDates
        Flux2025.H_QC: *Flux2025.inputDates
      minMax:
      - 0
      - 1
    LE:
      variableName: LE
      units: W m-2
      inputFiles:
        Flux2024.LE: *Flux2024.inputDates
        Flux2025.LE: *Flux2025.inputDates
      dependent:
      - LE_QC
      - H2O_signal
    LE_QC:
      variableName: LE_QC
      units: arb
      inputFiles:
        Flux2024.qc_LE: *Flux2024.inputDates
        Flux2025.LE_QC: *Flux2025.inputDates
      minMax:
      - 0
      - 1
    H2O_signal:
      variableName: H2O_signal
      units: umol mol-1
      inputFiles:
        Flux2024.h2o_signal: *Flux2024.inputDates
        Flux2025.H2O_sig_strgth_Min: *Flux2025.inputDates
    FCOC2:
      variableName: FCO2
      units: umol m-2 s-1
      inputFiles:
        Flux2024.co2_flux: *Flux2024.inputDates
        Flux2025.FCO2: *Flux2025.inputDates
      dependent:
      - FCO2_QC
      - CO2_signal
    FCO2_QC:
      variableName: FCO2_QC
      units: arb
      inputFiles:
        Flux2024.qc_co2_flux: *Flux2024.inputDates
        Flux2025.FC_QC: *Flux2025.inputDates
      minMax:
      - 0
      - 1
    CO2_signal:
      variableName: CO2_signal
      units: umol mol-1
      inputFiles:
        Flux2024.co2_signal: *Flux2024.inputDates
        Flux2025.CO2_sig_strgth_Min: *Flux2025.inputDates
      minMax:
      - 90
      - 110
    FCH4:
      variableName: FCH4
      units: umol m-2 s-1
      inputFiles:
        Flux2024.ch4_flux: *Flux2024.inputDates
        Flux2025.FCH4: *Flux2025.inputDates
      dependent:
      - FCH4_QC
      - CH4_signal
    FCH4_QC:
      variableName: FCH4_QC
      units: arb
      inputFiles:
        Flux2024.qc_ch4_flux: *Flux2024.inputDates
        Flux2025.FC_QC: *Flux2025.inputDates
    CH4_signal:
      variableName: CH4_signal
      units: umol mol-1
      inputFiles:
        Flux2024.diag_77_mean: *Flux2024.inputDates
        Flux2025.CH4_sig_strgth_Min: *Flux2025.inputDates
      minMax:
      - 20
      - 110
  SecondStage: {}
  ThirdStage: {}
